"""Initial schema

Revision ID: 5c3e27a5863e
Revises: 
Create Date: 2026-09-13 21:26:24.422693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3e27a5863e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('version_year', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('reporting_period', sa.String(length=100), nullable=False),
    sa.Column('annual_production', sa.Float(), nullable=False),
    sa.Column('production_unit', sa.String(length=50), nullable=False),
    sa.Column('selected_processes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    op.create_index(op.f('ix_factories_is_demo'), 'factories', ['is_demo'], unique=False)
    op.create_index(op.f('ix_factories_user_id'), 'factories', ['user_id'], unique=False)
    op.create_table('emission_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.Column('total_tco2e', sa.Float(), nullable=False),
    sa.Column('energy_tco2e', sa.Float(), nullable=False),
    sa.Column('material_tco2e', sa.Float(), nullable=False),
    sa.Column('waste_tco2e', sa.Float(), nullable=False),
    sa.Column('energy_pct', sa.Float(), nullable=False),
    sa.Column('material_pct', sa.Float(), nullable=False),
    sa.Column('waste_pct', sa.Float(), nullable=False),
    sa.Column('largest_source', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.Text(), nullable=True),
    sa.Column('factor_traceability', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_records_factory_id'), 'emission_records', ['factory_id'], unique=False)
    op.create_index(op.f('ix_emission_records_id'), 'emission_records', ['id'], unique=False)
    op.create_table('energy_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('annual_consumption', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('emission_factor', sa.Float(), nullable=False),
    sa.Column('factor_source', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_sources_factory_id'), 'energy_sources', ['factory_id'], unique=False)
    op.create_index(op.f('ix_energy_sources_id'), 'energy_sources', ['id'], unique=False)
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('branch_path', sa.String(length=150), nullable=False),
    sa.Column('carbon_tco2e', sa.Float(), nullable=False),
    sa.Column('share_pct', sa.Float(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('signal_value', sa.String(length=100), nullable=False),
    sa.Column('operating_condition', sa.String(length=150), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspots_factory_id'), 'hotspots', ['factory_id'], unique=False)
    op.create_index(op.f('ix_hotspots_id'), 'hotspots', ['id'], unique=False)
    op.create_table('material_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('annual_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('recycled_content_percent', sa.Float(), nullable=False),
    sa.Column('emission_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_inputs_factory_id'), 'material_inputs', ['factory_id'], unique=False)
    op.create_index(op.f('ix_material_inputs_id'), 'material_inputs', ['id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.String(length=150), nullable=True),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('primary_energy_source', sa.String(length=100), nullable=True),
    sa.Column('operating_pressure_bar', sa.Float(), nullable=True),
    sa.Column('estimated_leakage_percent', sa.Float(), nullable=True),
    sa.Column('annual_energy_kwh', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_factory_id'), 'processes', ['factory_id'], unique=False)
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('baseline_tco2e', sa.Float(), nullable=False),
    sa.Column('planned_saving_tco2e', sa.Float(), nullable=False),
    sa.Column('target_footprint_tco2e', sa.Float(), nullable=False),
    sa.Column('reduction_percent', sa.Float(), nullable=False),
    sa.Column('total_cost_inr_lakhs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_factory_id'), 'roadmaps', ['factory_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_table('waste_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(length=100), nullable=False),
    sa.Column('annual_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('treatment_method', sa.String(length=100), nullable=False),
    sa.Column('emission_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_streams_factory_id'), 'waste_streams', ['factory_id'], unique=False)
    op.create_index(op.f('ix_waste_streams_id'), 'waste_streams', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('hotspot_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_process', sa.String(length=100), nullable=False),
    sa.Column('root_cause', sa.String(length=150), nullable=False),
    sa.Column('carbon_saving_tco2e', sa.Float(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=False),
    sa.Column('estimated_cost_inr_lakhs', sa.Float(), nullable=False),
    sa.Column('payback_months', sa.Float(), nullable=False),
    sa.Column('effort_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('disruption_level', sa.String(length=50), nullable=False),
    sa.Column('assumption_reference', sa.Text(), nullable=True),
    sa.Column('derivation_type', sa.String(length=50), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_code'), 'recommendations', ['code'], unique=False)
    op.create_index(op.f('ix_recommendations_factory_id'), 'recommendations', ['factory_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('roadmap_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('action_title', sa.String(length=200), nullable=False),
    sa.Column('phase_label', sa.String(length=100), nullable=False),
    sa.Column('carbon_saving_tco2e', sa.Float(), nullable=False),
    sa.Column('cost_inr_lakhs', sa.Float(), nullable=False),
    sa.Column('effort_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_actions_id'), 'roadmap_actions', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_actions_roadmap_id'), 'roadmap_actions', ['roadmap_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('implementation_percent', sa.Float(), nullable=False),
    sa.Column('performance_percent', sa.Float(), nullable=False),
    sa.Column('cost_variation_percent', sa.Float(), nullable=False),
    sa.Column('effective_saving_tco2e', sa.Float(), nullable=False),
    sa.Column('future_footprint_tco2e', sa.Float(), nullable=False),
    sa.Column('reduction_percent', sa.Float(), nullable=False),
    sa.Column('estimated_cost_inr_lakhs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_factory_id'), 'scenarios', ['factory_id'], unique=False)
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_factory_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_roadmap_actions_roadmap_id'), table_name='roadmap_actions')
    op.drop_index(op.f('ix_roadmap_actions_id'), table_name='roadmap_actions')
    op.drop_table('roadmap_actions')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_factory_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_code'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_waste_streams_id'), table_name='waste_streams')
    op.drop_index(op.f('ix_waste_streams_factory_id'), table_name='waste_streams')
    op.drop_table('waste_streams')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_factory_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_factory_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_material_inputs_id'), table_name='material_inputs')
    op.drop_index(op.f('ix_material_inputs_factory_id'), table_name='material_inputs')
    op.drop_table('material_inputs')
    op.drop_index(op.f('ix_hotspots_id'), table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_factory_id'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_energy_sources_id'), table_name='energy_sources')
    op.drop_index(op.f('ix_energy_sources_factory_id'), table_name='energy_sources')
    op.drop_table('energy_sources')
    op.drop_index(op.f('ix_emission_records_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_factory_id'), table_name='emission_records')
    op.drop_table('emission_records')
    op.drop_index(op.f('ix_factories_user_id'), table_name='factories')
    op.drop_index(op.f('ix_factories_is_demo'), table_name='factories')
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
